export const BALCONY_META_TITLE = "Balcony Leak Repair Melbourne | 10 Year Warranty | Groutix";
export const BALCONY_META_DESCRIPTION = "We trace the source and fix failed grout, seals or membrane, often with no tile removal. 10 year warranty on eligible work. Free quote.";
export const balconyIntro = "Groutix repairs leaking balconies across Melbourne. We find where water gets in, then fix failed grout, seals or membranes. Many jobs need no tile removal. Eligible waterproof work carries a 10 year warranty, with scope confirmed in your free quote. We serve homes, apartments and strata buildings.";

export const balconyFaqs = [
  { q: "How much does balcony leak repair cost in Melbourne?", a: "It depends on size, cause and repair type. A simple regrout costs far less than a full membrane rebuild. Access matters too. High rise jobs can cost more than ground floor ones. We inspect free and give a fixed written quote. You know the price before we start." },
  { q: "Can a leaking balcony be repaired without removing tiles?", a: "Yes, in many cases. When the membrane under the tiles still holds, epoxy regrouting and resealing may fix the leak. Tiles stay in place. But a failed membrane needs tiles lifted for a rebuild. Our free inspection shows which one you need." },
  { q: "What causes balcony tiles to leak?", a: "Failed waterproof membranes, cracked grout, split movement joints and poor drainage can cause balcony leaks. UV damage wears out unsuitable sealants. Melbourne heat and rain speed up the wear. Most leaks come from a mix of these causes." },
  { q: "How long does a balcony leak repair take?", a: "The timeframe depends on balcony size, access and repair type. Regrouting and resealing take less time than a full rebuild with a new membrane. Your written quote states the timeframe and cure time upfront so you can plan around it. We tidy up before we leave." },
  { q: "How long before the balcony can be used after repair?", a: "Epoxy grout and sealants need time to cure fully. Walking on them too early can damage the finish. We tell you the exact wait before we start, based on the materials and weather conditions." },
  { q: "Do you service apartment balconies?", a: "Yes. We repair balconies in apartments, townhouses and houses across Melbourne. High rise or ground floor, we assess access and building requirements before work begins. We also work with strata managers and can discuss written reports for committees. One call books your free inspection." },
  { q: "Who fixes a leaking balcony, a plumber, waterproofer or grout specialist?", a: "It depends where the leak starts. Plumbers fix broken pipes. For leaks through grout, tiles and seals, a leak repair specialist is the right call. Failed membranes need an appropriately qualified waterproofer. We diagnose the source first, then recommend the right fix." },
  { q: "Is a balcony leak covered by strata insurance?", a: "Coverage depends on your policy, the cause of the leak and whether the affected area is common property. In Victoria, the plan of subdivision helps determine maintenance responsibility. Ask your owners corporation and insurer to confirm repair responsibility and coverage. We can discuss inspection photos and reporting requirements with you." },
];
